version: '3'
volumes:
  dados:
networks:
  banco:
  web:
services:
  database:
    image: postgres:10.3
    volumes:
      - dados:/var/lib/postgres/data
      # Scripts
      - ./scripts:/scripts
      # Execute scripts when start docker
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      # It belongs only to the network called 'banco'
      - banco
  frontend:
    image: nginx:1.13
    volumes:
      - ./web:/usr/share/nginx/html
      # Configuration of reverse proxy
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
    depends_on:
      # Orquestra a inicialiazação dos serviços começa pelo serviço que não depende de ninguém
      - app
  app:
    image: python:3.6
    volumes:
      - ./app:/app
    working_dir: /app
    # Should use the word bash to run as admin
    command: bash ./app.sh
    networks:
      - banco
      - web
    depends_on:
      - database
