version: '3'
volumes:
  dados:
services:
  database:
    image: postgres:10.3
    volumes:
      - dados:/var/lib/postgres/data
      # Scripts
      - ./scripts:/scripts
      # Execute scripts when start docker
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    image: nginx:1.13
    volumes:
      - ./web:/usr/share/nginx/html
    ports:
      - 80:80
  app:
    image: python:3.6
    volumes:
      - ./app:/app
    working_dir: /app
    # Should use the word bash to run as admin
    command: bash ./app.sh
    ports:
      - 8080:8080
